version: '2.2'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    volumes:
      - db-data:/var/lib/backup/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagosAsincronosDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3308"
    networks:
      - database

  springboot-rabbit:
    build:
      context: ./RabbitMQ
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pagosAsincronosDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - database
      - rabbit

  rabbitmq:
    image: rabbitmq:3.8.2
    container_name: rabbitmq_container
    ports:
      - "5673:5673"
    networks:
      - rabbit

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9201"
      - "9301:9301"
    networks:
      - elastic

  spring-websocket:
    build:
      context: ./springBootWebsocket/WebSocket
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - elasticsearch
      - rabbitmq
    networks:
      - fronted
      - elastic
      - rabbit
      - database

  angular:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    networks:
      - fronted
  

volumes:
  db-data:

networks:
  fronted: 
    driver: bridge  
  elastic: 
    driver: bridge  
  rabbit: 
    driver: bridge   
  database: 
    driver: bridge
