version: '2.2'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    volumes:
      - db-data:/var/lib/backup/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagosAsincronosDB
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - database

  rabbitmq:
    image: rabbitmq:3.8.2
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
    networks:
      - rabbit

  angular:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    networks:
      - frontend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
    mem_limit: 1g 
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  springboot-rabbit:
    build:
      context: ./RabbitMQ
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/pagosAsincronosDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - database
      - rabbit
  
  spring-websocket:
    build:
      context: ./springBootWebsocket/WebSocket
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - elasticsearch
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/pagosAsincronosDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES: elasticsearch_container:9200
    networks:
      - frontend
      - elastic
      - rabbit
      - database

volumes:
  db-data:

networks:
  frontend: 
    driver: bridge  
  elastic: 
    driver: bridge  
  rabbit: 
    driver: bridge   
  database: 
    driver: bridge
